### ISSUE TITLE
node.serializeToString is not a function

### ISSUE THREAD

**Issue by ghazal-karami** [bdukes/grunt-xmlpoke#12]
Hi,

I am getting "node.serializeToString is not a function" on "npm install", after upgarding npm to 3.3.12 and node to v5.4.0.

**Comment by bdukes** [comment]
I'm assuming this is the same issue that's fixed by #11, so you can use that as a workaround until the fixed version is out

**Comment by bdukes** [comment]
if you run `npm install` again, you should get xmldom version 0.1.21 now (instead of 0.1.20, which causes this problem), and that will fix this issue.
