### ISSUE TITLE
xlmns related problem

### ISSUE THREAD

**Issue by zarko-tg** [bdukes/grunt-xmlpoke#15]
It seems something has been broken with 8.0.1.

Say you want to replace the value for "version" given the following content:

    <widget xmlns="http://www.w3.org/ns/widgets" version="" />

It basically fails with
>Warning: No node matched the XPath expression `/widget/@version`

and the resulting file doesn't get generated.

(It does work as intended without the `xmlns="..."`)

8.0.0 works as expected.

**Comment by bdukes** [comment]
Version 8.0.1 included an update to the `xpath` package, which fixed the bug which ignored `xmlns` declarations.  You'll need to declare and use a namespace prefix in your xpath:

```
namespaces: {
    dest: 'dist/widget.xml',
    src: 'src/widget.xml',
    options: {
        namespaces: {
            'w': 'http://www.w3.org/ns/widgets'
        },
        xpath: '/w:widget/@version',
        value: '1.2.4'
    }
}
```

Sorry for the churn in your code, but it wasn't behaving correctly before (and, ultimately, the change is from [`xpath`](https://www.npmjs.com/package/xpath)).  Hope it helps.

**Comment by zarko-tg** [comment]
Thanks, that wasn't very obvious.
But how about if you have the following which is common for a Cordova app/project:
```
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" version="">
  <name></name>
</widget>
```
and want to replace the value for name?
How do you refer to it with xpath, or/and how do set up the namespace?

**Comment by bdukes** [comment]
The `xmlns` attribute defines the default namespace, so `http://www.w3.org/ns/widgets` applies to both `widget` and `name` (but if it was `<cdv:name />` then the other namespace would apply).  When you're defining the list of namespaces in the xmlpoke options, the prefixes there are arbitrary (e.g. you could name `http://cordova.apache.org/ns/1.0` `cordova` instead of `cdv`), so you just need to define a prefix for the `http://www.w3.org/ns/widgets` namespace and use that in your xpath for both elements:

```
widget: {
    dest: 'dist/widget.xml',
    src: 'src/widget.xml',
    options: {
        namespaces: {
            'w': 'http://www.w3.org/ns/widgets',
            'cdv': 'http://cordova.apache.org/ns/1.0'
        },
        xpath: '/w:widget/w:name',
        value: 'the name'
    }
}
```

Hope it helps!

**Comment by zarko-tg** [comment]
Sweet! The answer was all I could hope for.

Maybe the documentation can be expanded with a little example on this matter if others end up looking here. But at least I consider this case closed now.

Thanks a lot again
