### ISSUE TITLE
replacements broken in 0.8.1+

### ISSUE THREAD

**Issue by nickcmaynard** [bdukes/grunt-xmlpoke#25]
In 0.8.1, and 0.8.2, replacements specified in the `replacements` array no longer work.  This used to work OK in 0.8.0.

**Comment by bdukes** [comment]
Does your document have an `xmlns`?  The `xpath` dependency that this plugin uses was updated to fix the bug where it ignored `xmlns` declarations.  Take a look at https://github.com/bdukes/grunt-xmlpoke/issues/15 for details.

**Comment by nickcmaynard** [comment]
You're absolutely right.  Duplicate of #15.  Shame (for simplicity of use) there's no way to ignore namespaces.  Many docs only have one.
