### ISSUE TITLE
Problem on access to an xml with widget

### ISSUE THREAD

**Issue by mtizziani** [bdukes/grunt-xmlpoke#31]
i have an xml looking like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <widget param1="12">
        <title>I want to be changed</title>
    </widget>

with your plugin i cant change anything. looks for me like `xpath: "/widget"`breaks

i also tried `xpath: 'widget'` as selector and `xpath: "title"` nothing works.

on other xml files like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <bookmark>
        <mynode>test</mynode>
    </bookmark>

all works fine

**Comment by bdukes** [comment]
Do you need to use `xpath: "/widget/title"`?  See the example test I just committed

**Comment by bdukes** [comment]
Let me know if there's a different scenario that's not covered by that test that you're expecting to work.  Thanks!

**Comment by mtizziani** [comment]
i found the failure:

    <widget id="com.cordova.io" version="3.0.2" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">

this did not work because of `xmlns="http://www.w3.org/ns/widgets"`

if i kill this statement it works now, so i have to kill it from my default cordova config and insert the attribute when i edited all other parameters

**Comment by bdukes** [comment]
you just need to include that namespace in your config (see the [namespaces example](/bdukes/grunt-xmlpoke/blob/1a2572fce97b169c308bdf75b892c4969fcb8cbd/Gruntfile.js#L183-L194)):

```
widget: {
    dest: 'dist/widget.xml',
    src: 'src/widget.xml',
    options: {
        namespaces: {
            'w': 'http://www.w3.org/ns/widgets',
            'cdv': 'http://cordova.apache.org/ns/1.0'
        },
        xpath: '/w:widget/w:title',
        value: 'New Title'
    }
},
```

**Comment by bdukes** [comment]
Also, see the newly added documentation about the `xmlns` attribute in c1771a8.  Let me know if there's anything else that would help clarify.  Thanks!

**Comment by mtizziani** [comment]
thats excatly what i was looking for, big thanks
