### ISSUE TITLE
Proper Error Handling

### ISSUE THREAD

**Issue by sebbi08** [bdukes/grunt-xmlpoke#52]
Given

```
files: {
    "temp.xml": dest + "Path/to/non/existing/file.404"
}
```

will result in an error:
```
[xmldom error]	invalid doc source 
@#[line:0,col:undefined]
```

would be nice to do an grunt.file.exists(path) check and handing out an  proper error message

**Comment by bdukes** [comment]
I've found the issue, I didn't understand how Grunt handled missing files.  I'll push out 0.10.0 soon, after 4430552e4cc04b0abf6e7aeb0e5cc37eb3079227 is validated

**Comment by sebbi08** [comment]
Ah nice to see that, diden't know that too.

Tank you
