### ISSUE TITLE
Interrupt the task when xpath not found

### ISSUE THREAD

**Issue by omatrycy** [bdukes/grunt-xmlpoke#9]
Hello

I'am using this task to change configuration in xml files. Actually when xpath is not found task continues working. I'll added new feature: when xpath is not found task interrupt working, show bad xpath and return false. This option schould be configured by global, section (files) or single xpath. Default disable for backward compatibility. 

What do you think about this change?

Best wishes

**Comment by bdukes** [comment]
That sounds good to me.  You should be able to add `throwIfMissing: true` to either a top-level options object or a task-level options object.  I'm not sure how you would indicate that for a single xpath (other than making it its own task).

**Comment by omatrycy** [comment]
Mayby that:

```php
// ...
var select = options.namespaces ? xpath.useNamespaces(options.namespaces) : xpath.select;
var nodes = select(query, doc);

//ADD THIS break if node no exist
if ((options.throwIfMissing || replacement.throwIfMissing) && (nodes == null || nodes.length === 0)) {
    grunt.fail.fatal("No found xpath " + query.blue);
}

nodes.forEach(function (node) {
// ...
```

grunt file : 
```javascript
xmlpoke: {
  task: {
    src: 'config.xml',
    dest: 'config.xml',
    options: {
      replacements: {
        throwIfMissing : true,
        xpath: '/x/@z',
        value: '8708'
      }
    }
  }
}
```

or : 
```javascript
xmlpoke: {
  options : {
    throwIfMissing : true,
  },
  task: {
    src: 'config.xml',
    dest: 'config.xml',
    options: {
      replacements: {
        xpath: '/x/@z',
        value: '8708'
      }
    }
  }
}
```

or 
```javascript
xmlpoke:
  task: {
    src: 'config.xml',
    dest: 'config.xml',
    options: {
      throwIfMissing : true,
      replacements: {
        xpath: '/x/@z',
        value: '8708'
      }
    }
  }
}
```

I cannot write tests for this solution, when using grunt.fail.fatal.

**Comment by bdukes** [comment]
Thanks, I've added it as version 0.8.0 and published to NPM (I changed the option name to `failIfMissing` after reviewing everything).  Thanks for the idea and the code.
